spring.config.import=file:env.properties
spring.application.name=BookATable
server.port=${PORT}
# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
# JWT CONFIG
jwt.secret=${JWT_SECRET}
# SWAGGER CONFIG
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
# Queste due righe sotto permettono di poter scrivere nel body di una request un valore appartenente a un ENUM anche in minuscolo
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.mapper.accept-case-insensitive-enums=true
# OpenWeather API Key
openweather_key=${OPENWEATHER_KEY}